# Generated by Django 3.2.4 on 2021-06-30 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('country', models.CharField(max_length=100, verbose_name='Country Name')),
                ('medicine', models.CharField(max_length=100, verbose_name='Medicine Name')),
                ('phone', models.IntegerField(verbose_name='Phone Number')),
                ('zipcode', models.IntegerField(verbose_name='Zip Code')),
            ],
        ),
        migrations.CreateModel(
            name='CardDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardname', models.CharField(max_length=100, verbose_name='Card Holder Name')),
                ('cardnumber', models.IntegerField(verbose_name='Credit Card Number')),
                ('month', models.IntegerField(max_length=2, verbose_name='Exp Month')),
                ('year', models.IntegerField(max_length=4, verbose_name='Exp Year')),
                ('civ', models.IntegerField(max_length=3, verbose_name='CIV')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Message')),
            ],
        ),
    ]
