# Generated by Django 3.2.4 on 2021-06-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddetail',
            name='civ',
            field=models.IntegerField(verbose_name='CIV'),
        ),
        migrations.AlterField(
            model_name='carddetail',
            name='month',
            field=models.IntegerField(verbose_name='Exp Month'),
        ),
        migrations.AlterField(
            model_name='carddetail',
            name='year',
            field=models.IntegerField(verbose_name='Exp Year'),
        ),
    ]
