# Generated by Django 3.2.4 on 2021-06-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0002_auto_20210630_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddetail',
            name='civ',
            field=models.IntegerField(verbose_name='CVV'),
        ),
    ]
