# Generated by Django 3.2.4 on 2021-07-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0006_alter_carddetail_civ'),
    ]

    operations = [
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('ngoname', models.EmailField(max_length=100, verbose_name='NGO Name')),
                ('ngonumber', models.EmailField(max_length=100, verbose_name='NGO Number')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('country', models.CharField(max_length=100, verbose_name='Country Name')),
                ('city', models.CharField(max_length=100, verbose_name='City Name')),
                ('medicine', models.CharField(max_length=100, verbose_name='Medicine Name')),
                ('medicinedate', models.CharField(max_length=100, verbose_name='Medicine Expiration Date')),
                ('medicineqty', models.CharField(max_length=100, verbose_name='Medicine Quantity')),
                ('medicinetype', models.CharField(max_length=100, verbose_name='Medicine Quantity Type')),
                ('phone', models.IntegerField(verbose_name='Phone Number')),
                ('zipcode', models.IntegerField(verbose_name='Zip Code')),
            ],
        ),
        migrations.AddField(
            model_name='addres',
            name='city',
            field=models.CharField(default='lah', max_length=100, verbose_name='City Name'),
        ),
        migrations.AddField(
            model_name='addres',
            name='medicinedate',
            field=models.CharField(default='21', max_length=100, verbose_name='Medicine Expiration Date'),
        ),
        migrations.AddField(
            model_name='addres',
            name='medicineqty',
            field=models.CharField(default='2', max_length=100, verbose_name='Medicine Quantity'),
        ),
        migrations.AddField(
            model_name='addres',
            name='medicinetype',
            field=models.CharField(default='2', max_length=100, verbose_name='Medicine Quantity Type'),
        ),
    ]
