# Generated by Django 3.2.4 on 2021-07-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0008_auto_20210704_0030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('country', models.CharField(max_length=100, verbose_name='Country Name')),
                ('city', models.CharField(max_length=100, verbose_name='City Name')),
                ('medicine', models.CharField(max_length=100, verbose_name='Medicine Name')),
                ('medicinedate', models.CharField(max_length=100, verbose_name='Medicine Expiration Date')),
                ('medicineqty', models.CharField(max_length=100, verbose_name='Medicine Quantity')),
                ('medicinetype', models.CharField(max_length=100, verbose_name='Medicine Quantity Type')),
                ('phone', models.CharField(max_length=100, verbose_name='Phone Number')),
                ('zipcode', models.CharField(max_length=100, verbose_name='Zip Code')),
                ('cardname', models.CharField(default='8', max_length=100, verbose_name='Card Holder Name')),
                ('cardnumber', models.CharField(default='8', max_length=100, verbose_name='Credit Card Number')),
                ('month', models.CharField(default='8', max_length=100, verbose_name='Exp Month')),
                ('year', models.CharField(default='8', max_length=100, verbose_name='Exp Year')),
                ('civ', models.CharField(default='8', max_length=100, verbose_name='CVV')),
            ],
        ),
        migrations.DeleteModel(
            name='Addres',
        ),
        migrations.AddField(
            model_name='ngo',
            name='cardname',
            field=models.CharField(default='8', max_length=100, verbose_name='Card Holder Name'),
        ),
        migrations.AddField(
            model_name='ngo',
            name='cardnumber',
            field=models.CharField(default='8', max_length=100, verbose_name='Credit Card Number'),
        ),
        migrations.AddField(
            model_name='ngo',
            name='civ',
            field=models.CharField(default='8', max_length=100, verbose_name='CVV'),
        ),
        migrations.AddField(
            model_name='ngo',
            name='month',
            field=models.CharField(default='8', max_length=100, verbose_name='Exp Month'),
        ),
        migrations.AddField(
            model_name='ngo',
            name='year',
            field=models.CharField(default='8', max_length=100, verbose_name='Exp Year'),
        ),
        migrations.AlterField(
            model_name='carddetail',
            name='cardnumber',
            field=models.CharField(max_length=100, verbose_name='Credit Card Number'),
        ),
        migrations.AlterField(
            model_name='carddetail',
            name='civ',
            field=models.CharField(max_length=100, verbose_name='CVV'),
        ),
        migrations.AlterField(
            model_name='carddetail',
            name='month',
            field=models.CharField(max_length=100, verbose_name='Exp Month'),
        ),
        migrations.AlterField(
            model_name='carddetail',
            name='year',
            field=models.CharField(max_length=100, verbose_name='Exp Year'),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='ngoname',
            field=models.CharField(max_length=100, verbose_name='NGO Name'),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='ngonumber',
            field=models.CharField(max_length=100, verbose_name='NGO Number'),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='zipcode',
            field=models.CharField(max_length=100, verbose_name='Zip Code'),
        ),
    ]
