# Generated by Django 3.2.4 on 2021-07-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0009_auto_20210704_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='cardname',
            field=models.CharField(max_length=100, verbose_name='Card Holder Name'),
        ),
        migrations.AlterField(
            model_name='buy',
            name='cardnumber',
            field=models.CharField(max_length=100, verbose_name='Credit Card Number'),
        ),
        migrations.AlterField(
            model_name='buy',
            name='civ',
            field=models.CharField(max_length=100, verbose_name='CVV'),
        ),
        migrations.AlterField(
            model_name='buy',
            name='month',
            field=models.CharField(max_length=100, verbose_name='Exp Month'),
        ),
        migrations.AlterField(
            model_name='buy',
            name='year',
            field=models.CharField(max_length=100, verbose_name='Exp Year'),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='cardname',
            field=models.CharField(max_length=100, verbose_name='Card Holder Name'),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='cardnumber',
            field=models.CharField(max_length=100, verbose_name='Credit Card Number'),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='civ',
            field=models.CharField(max_length=100, verbose_name='CVV'),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='month',
            field=models.CharField(max_length=100, verbose_name='Exp Month'),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='year',
            field=models.CharField(max_length=100, verbose_name='Exp Year'),
        ),
    ]
